name: Build Spring Boot App

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Upload JAR to JFrog Artifactory
        run: |
          curl -u "${{ secrets.JFROG_USERNAME }}:${{ secrets.JFROG_API_KEY }}" \
            -T "/home/runner/.m2/repository/com/india/railway/IndianRailway/0.0.1-SNAPSHOT/IndianRailway-0.0.1-SNAPSHOT.jar" \
            "${{ secrets.JFROG_URL }}/${{ secrets.JFROG_REPO }}/com/india/railway/IndianRailway/0.0.1-SNAPSHOT/IndianRailway-0.0.1-SNAPSHOT.jar"
